# Welcome to Jekyll!
#

# Site settings
title: Lukas Lernt Malen
description: Ein videobasierter Guide zum Bemalen von Miniaturen!
owner: Julian Staab
first_published: 2022 
email: julianstaab@web.de
baseurl: "/LukasLerntMalen" # the subpath of your site, e.g. /blog
url: "http://emiliehk.github.io" # the base hostname & protocol for your site
social:
  github: https://github.com/EmilieHK/LukasLerntMalen
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
